name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install kernel headers
        run: |
          sudo apt-get update
          sudo apt-get -y install linux-headers-$(uname -r)

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: make
