name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04

    steps:
      - name: Install kernel headers
        run: |
          sudo apt-get update
          sudo apt-get -y install linux-headers-$(uname -r)

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: make
